name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      # Add your environment variables here, based on .env.example
      # SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      # SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      #- name: Lint
      #  run: npm run lint

      #- name: Format check
      #  run: npm run format

      - name: Run unit tests
        run: npm run test

      #- name: Install Playwright browsers
      #  run: npx playwright install --with-deps

      #- name: Run e2e tests
      #  run: |
      #    npm run dev:e2e &
      #    npm run test:e2e

      - name: Build
        run: npm run build
